version: "3.8"

services:
  jboss_jbpm_server:
    image: ghcr.io/joseesco24/jboss_jbpm_server:latest
    build:
      context: .././containers/jboss_jbpm_server/
      dockerfile: ./Dockerfile

  jboss_jbpm_database:
    image: ghcr.io/joseesco24/jboss_jbpm_database:latest
    build:
      context: .././containers/jboss_jbpm_database/
      dockerfile: ./Dockerfile
